#!/bin/bash

set -Eeu -o pipefail

IMAGE_NAME="vagrant"
REPOSITORY="ghcr.io/moritzheiber"
GIT_BRANCH=$(git branch --show-current)
TARGET="latest"
REV=$(git rev-parse --short HEAD)

if ! [ "${GIT_BRANCH}" == "main" ] ; then
  TARGET="${GIT_BRANCH}"
fi

CONTAINER="${IMAGE_NAME}:${TARGET}"

build() {
  docker build -t "${CONTAINER}" .

  docker tag "${CONTAINER}" "${REPOSITORY}/${CONTAINER}"
  docker tag "${CONTAINER}" "${REPOSITORY}/${IMAGE_NAME}:${REV}"
}

push() {
  docker push "${REPOSITORY}/${CONTAINER}"
  docker push "${REPOSITORY}/${IMAGE_NAME}:${REV}"
}

usage() {
  echo "Usage ${0} build | push"
  exit 1
}

CMD=${1:-}
shift || true
case ${CMD} in
  build) build ;;
  push) push ;;
  *) usage ;;
esac
