name: build-push
on:
  push:
    branches:
      - main
      - focal
      - lunar
    tags-ignore:
      - "*"

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Set tag name
        id: tag
        run: echo "name=ghcr.io/moritzheiber/vagrant:${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - uses: e1himself/goss-installation-action@v1.1.0
      - uses: docker/setup-buildx-action@v2
      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          tags: ${{ steps.tag.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: dgoss run --rm ${{ steps.tag.outputs.name }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.tag.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
